#!/bin/bash

appdir=$(pwd)


if [[ -z $1 ]]; then
    echo "Error : need additional paramater"
fi


if [[ $1 == "--reset" ]];then
    /bin/bash /install/library/installs/setups &&
    exit
fi


if [[ $1 == "--install" ]];then
    /bin/bash /install/library/installs/setups --purge &&
    exit
fi


if [[ $1 == "--testing" ]];then
    /bin/bash /install/library/installs/setups --teste &&
    exit
fi


if [[ $1 == "--build" ]];then
    /bin/bash $appdir/library/builder/isogen $appdir &&
    exit
fi


if [[ $1 == "--getapp" ]];then
    /bin/bash $appdir/library/builder/ipkgen $appdir &&
    exit
fi


if [[ $1 == "--deploy" ]];then
    /bin/bash $appdir/library/deploy/uploads $appdir &&
    exit
fi


if [[ $1 == "--gitpush" ]];then
    /bin/bash $appdir/library/helper/gitpush $appdir &&
    exit
fi