#!/bin/bash

appdir=$(pwd)


if [[ -z $1 ]]; then
    echo "Error : command need additional paramater"
fi

if [[ $1 == "--install" ]];then
    /bin/bash /install/library/installs/setups --purge &&
    exit
fi

if [[ $1 == "--reset" ]];then
    /bin/bash /install/library/installs/setups $appdir &&
    exit
fi

if [[ $1 == "--build" ]];then
    /bin/bash $appdir/library/builder/isogen $appdir &&
   exit
fi

if [[ $1 == "--getapp" ]];then
    /bin/bash $appdir/library/builder/ipkgen $appdir &&
    exit
fi


if [[ $1 == "--deploy" ]];then
    /bin/bash $appdir/library/deploy/server $appdir &&
    exit
fi


if [[ $1 == "--update" ]];then
    /bin/bash $appdir/library/helper/uprepo $appdir &&
    exit
fi