#!/bin/bash

PACKAGE="${PACKAGE} flatpak firefox fuse btop evolution keepassxc virt-manager libvirt qemu-desktop podman podman-desktop docker nginx code hugo go apparmor lvm2 testdisk btrfs-progs xfsprogs ntfs-3g dosfstools ethtool rsync grsync grafana "
RDAEMON="${RDAEMON} nginx libvirtd docker.socket grafana.service "
GDAEMON="${GDAEMON}"